name: Calculator Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: get secret value
        env:
           DB_USERNAME_KEY : ${{secret.DB_USERNAME}}
        run: python test.py 

      

